config/routes.rb
Rails.application.routes.draw do
  resources :posts do 
    resources :comments, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  default_scope { order(created_at: :desc)}
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale


  private 
  
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    if !@comment.save
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @comment.errors, status: :unprocessable_entity }
    end

    redirect_to @post
  end


  private
    def comment_params
      params.require(:comment).permit(:body, :name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def date_day_month_year(date)
    date.strftime("%B %d, %Y") 
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>" class="comment">
  <div>
    <p>
      <%= comment.body %>
    </p>
    <span><%= comment.name %> - <%= date_day_month_year(comment.created_at)%></span>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with url: post_comments_path(@post), method: :post do |form|%>
  <div>
    <%= form.label :name, "Comment Title"%>
    <%= form.text_field :name, name: "comment[name]" %>
  </div>

  <div>
    <%= form.label :body, "Comment Body"%>
    <%= form.text_area :body, name: "comment[body]" %>
  </div>

  <div>
    <%= form.submit "Submit" %>
  </div>
<%end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= link_to "Blog", root_path %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label t('posts.title'), style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label t('posts.body'), style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= link_to post do %>
      <div class="post">
        <h3>
          <%= post.title %>
        </h3>
        <span>Read more → </span>
      </div>
    <% end %>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @post.title %></h1>

<p>
<%= @post.body%>
</p>

<div class="comments-section">
  <h2>Comments:</h2>
  
  <%= render partial: "comments/form" %>

  <%# render @post.comments.order(created_at: :desc) %>
  <%= render @post.comments %>

</div>


<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>